# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
       tag_name: ${{ github.ref }}
       release_name: Release ${{ github.ref }}
       body: |
          Changes in this Release
          - First Change
          - Second Change
       draft: false
       prerelease: false
    - name: Set up our custom Artifactory instance
      uses: actions/setup-java@v1
      with: # running setup-java again overwrites the settings.xml
        java-version: 11
        server-id: artifactory # value of repository/id field of the pom.xml
        server-username: ARTIFACTORY_USERNAME_REF  # env variable name for username of Artifactory server; value can be anything as it is a transient user
        server-password: ARTIFACTORY_TOKEN_REF # env variable name for Artifactory access token
        # after running this action, the <username> tag contains ${env.ARTIFACTORY_USERNAME_REF} and <password> contains ${env.ARTIFACTORY_TOKEN_REF}
 
    - name: Build with Maven
      run: mvn -B package
      env:
        # assign the environment variable env.ARTIFACTORY_TOKEN_REF with the previously configured ARTIFACTORY_TOKEN
        ARTIFACTORY_TOKEN_REF: ${{ secrets.ART_TOKEN }}
        # assign the environment variable env.ARTIFACTORY_USERNAME_REF with the previously configured ARTIFACTORY_USERNAME
        ARTIFACTORY_USERNAME_REF: ${{ secrets.ART_USERNAME }}
